<a href="https://colab.research.google.com/github/glenda2912/Tous12/blob/main/03_Data_Strcutures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **1. What is a DS?**

A DS is an object that let us store more than one value. 

Formally, a DS is **sequence** of values which can be located with an index. 



# **2. Lineal Algebra**

## 2.1 What is Numpy? 

Numpy (Numerical Python) is a collection on fuctions and methods. 



In [2]:
# Install the library 

import numpy as np

## 2.2 Numpy arrays - vectors and matrices 

*Example 1 - Colum vector*



In [ ]:
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


*Example 2 - Row vector*

In [ ]:
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


*Example 3 - Matrix*

In [ ]:
M = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# nice trick

nr, nc = M.shape

# 2.3 Sciling 

To access a one or several elements of the object. 

In [ ]:
# Extract the first element 

## Column vector 
print(a[0,0])

## Row vector 
print(b[0,0])

## Matriz 
print(M[0,0])


1
4
1


In [ ]:
# Extract the last element

## Column vector 
print(a[-1,0])

## Row vector 
print(b[0,-1])

## Matrix 
print(M[-1,-1])


3
6
9


In [ ]:
# Extract a subset

## Column vector 
print(a[0:2])

## Row vector 
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[1]
 [2]]
[4 5]
[[1 2]
 [4 5]]


# 2.4 Methods 

In [ ]:
 # ZEROS 

z1 = np.zeros(4)
print(z1) 

z2 = np.zeros((3,2))
print(z2)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# ONES 

o1 = np.ones(4)
print(o1) 

o2 = np.ones((3,2))
print(o2)

o2*5


[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**

In [ ]:
# Full 

f = np.full((3,2),5)
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [ ]:
# Lineal sequence 

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)


array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [ ]:
# Lineal space 

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5 Random Numbers 


In [ ]:
# A single Value - Between 0 and 1
np.random.seed(1234)
np.random.rand()

0.1915194503788923

In [ ]:
# Example - toss a coin 

if np.random.rand() < 0.5:
  print('head')
else: 
  print('tails')

head


In [ ]:
# Two heads in a row 

if np.random.rand() < 0.25:
  print('You win!')
else: 
  print('You lose!')

You lose!


In [ ]:
# Two heads in a row 

ft = np.random.rand()
if ft < 0.5:
  print('The first toss was Head')
else: 
  print('The first toss was Tails')

st = np.random.rand()
if st < 0.5:
  print('The second toss was Head')
else: 
  print('The second toss was Tails')

if ft < 0.5 and st < 0.5: 
  print('You win!')
else: 
  print('You lose!')

The first toss was Tails
The second toss was Tails
You lose!


In [3]:
# One dimensional array
np.random.rand(5)

array([0.47113616, 0.6694449 , 0.945486  , 0.48863366, 0.96666731])

In [4]:
# Matrix
np.random.rand(6,2)

array([[0.41068883, 0.84145084],
       [0.74168412, 0.18997868],
       [0.03508449, 0.06560198],
       [0.67197605, 0.64979439],
       [0.61879447, 0.93776   ],
       [0.93086356, 0.04515885]])

### Uniform distribution [a,b)

In [5]:
# Single value
np.random.uniform(low = -10, high = 0)

-1.3033800057549598

In [6]:
# One dimensional array
np.random.uniform(low = -10, high = 0, size = 7)

array([-4.20290744, -9.81156526, -5.87456922, -5.28803295, -1.08236366,
       -5.05396807, -0.07334625])

In [7]:
# Matrix
np.random.uniform(low = -10, high = 0, size = (5,1))

array([[-3.09528014],
       [-6.07428444],
       [-4.28079216],
       [-9.00922255],
       [-1.77211396]])

** Exercise**

Simulate the sale of a shop according to

| Scenario | Prob | Sales |
|----------|------|-------|
| Bad      | 25%  | 60    |
| Normal   | 50%  | 80    |
| Wow      | 25%  | 100   |

For 5 days.

In [8]:
# A Solution

for i in range(1,6):
  tmp = np.random.rand()
  if tmp <0.25:
    print('Day:',i,'Scenario: Bad','Units sold: 60')
  elif tmp>0.75:
    print('Day:',i,'Scenario: Wow','Units sold: 100')
  else:
    print('Day:',i,'Scenario: Normal','Units sold: 80')

Day: 1 Scenario: Normal Units sold: 80
Day: 2 Scenario: Bad Units sold: 60
Day: 3 Scenario: Normal Units sold: 80
Day: 4 Scenario: Normal Units sold: 80
Day: 5 Scenario: Normal Units sold: 80
